<div class="page-header">
  <h1>Edit subscription period</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
  
	<div class="form-group <?php e(isset($errors['subscriptionperiods[name]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptionperiods[name]">Name</label>
		<input class="form-control" name="subscriptionperiods[name]" type="text" value="<?php e($data['subscriptionperiods']['name']); ?>" id="subscriptionperiods[name]" />
		<span class="help-block"><?php if (isset($errors['subscriptionperiods[name]'])) e($errors['subscriptionperiods[name]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['subscriptionperiods[comment]'])?'has-error':''); ?>">
		<label class="control-label" for="subscriptionperiods[comment]">Comment</label>
		<input class="form-control" name="subscriptionperiods[comment]" type="text" value="<?php e($data['subscriptionperiods']['comment']); ?>" id="subscriptionperiods[comment]" />
		<span class="help-block"><?php if (isset($errors['subscriptionperiods[comment]'])) e($errors['subscriptionperiods[comment]']); ?></span>
	</div>

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 