<h1>Subscription periods <a class="btn-primary" href="subscriptionperiods/add">Add subscription period</a></h1>
<table class="table responsive-minimal">
  <thead>
    <tr>
      <th class="date">From</th>
      <th class="name">Name</th>
      <th>Subscription</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($data as $row): ?>
    <tr class="hover" onclick="window.location.href='subscriptionperiods/view/<?php e($row['subscriptionperiods']['id']);?>';">
      <td class="date"><span><?php e($row['subscriptionperiods']['from']);?></span></td>
      <td class="name"><span><?php e($row['subscriptionperiods']['name']);?></span></td>
      <td><span><a href="subscriptions/view/<?php e($row['subscriptionperiods']['subscription_id']);?>"><?php e($subscriptions[$row['subscriptionperiods']['subscription_id']]);?></a></span></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<p><a class="btn-primary" href="subscriptionperiods/add">Add subscription period</a></p>