<?php Buffer::set('title','Add invoice'); ?>
<div class="page-header">
	<h3><a href="/">Home</a> / <a href="invoices">Invoices</a></h3>
  	<h1>Add invoice</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">

	<div class="form-group <?php e(isset($errors['invoices[name]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[name]">Name</label>
		<input class="form-control" name="invoices[name]" type="text" value="<?php e($data['invoices']['name']); ?>" id="invoices[name]" />
		<span class="help-block"><?php if (isset($errors['invoices[name]'])) e($errors['invoices[name]']); ?></span>
	</div>

	<br />

	<table class="table">
		<thead>
			<tr>
				<th class="name" colspan="2">Invoice lines</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($invoicelines as $key=>$invoiceline): ?>
			<tr>
				<td class="name"><span><input name="invoicelines[]" type="checkbox" value="<?php e($key);?>" checked /> &nbsp; <?php e($invoiceline['name']);?></span></td>
				<td class="money"><span><?php e($invoiceline['subtotal']);?></span></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<br /><br />

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>

</form> 
