<?php Buffer::set('title','Add invoice'); ?>
<div class="page-header">
	<h3><a href="/">Home</a> / <a href="invoices">Invoices</a></h3>
  	<h1>Add invoice</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">

	<div class="form-group <?php e(isset($errors['invoices[customer_id]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[customer_id]">Customer</label>
		<select class="form-control" name="invoices[customer_id]" id="invoices[customer_id]">
			<option value=""></option>
			<?php foreach ($customers as $customer): ?>
			<option value="<?php e($customer['customers']['id']); ?>"><?php e($customer['customers']['name']); ?></option>
			<?php endforeach; ?>
		</select>
		<span class="help-block"><?php if (isset($errors['invoices[customer_id]'])) e($errors['invoices[customer_id]']); ?></span>
	</div>

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form>
