<?php Buffer::set('title','Edit invoice'); ?>
<div class="page-header">
	<h3><a href="/">Home</a> / <a href="invoices">Invoices</a></h3>
  	<h1>Edit invoice</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
  
	<div class="form-group <?php e(isset($errors['invoices[number]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[number]">Number</label>
		<input class="form-control" name="invoices[number]" type="number" value="<?php e($invoice['invoices']['number']); ?>" id="invoices[number]" disabled />
		<span class="help-block"><?php if (isset($errors['invoices[number]'])) e($errors['invoices[number]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['invoices[name]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[name]">Name</label>
		<input class="form-control" name="invoices[name]" type="text" value="<?php e($data['invoices']['name']); ?>" id="invoices[name]" />
		<span class="help-block"><?php if (isset($errors['invoices[name]'])) e($errors['invoices[name]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['invoices[date]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[date]">Date</label>
		<input class="form-control" name="invoices[date]" type="date" value="<?php e($data['invoices']['date']); ?>" id="invoices[date]" />
		<span class="help-block"><?php if (isset($errors['invoices[date]'])) e($errors['invoices[date]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['invoices[sent]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[sent]">Sent</label>
		<input class="form-control" name="invoices[sent]" type="checkbox" <?php if($data['invoices']['sent']) e('checked'); ?> id="invoices[sent]" value="1" />
		<span class="help-block"><?php if (isset($errors['invoices[sent]'])) e($errors['invoices[sent]']); ?></span>
	</div>

	<?php if($data['invoices']['sent']) { ?>
		<div class="form-group <?php e(isset($errors['invoices[paid]'])?'has-error':''); ?>">
			<label class="control-label" for="invoices[paid]">Paid</label>
			<input class="form-control" name="invoices[paid]" type="checkbox" <?php if($data['invoices']['paid']) e('checked'); ?> id="invoices[paid]" value="1" />
			<span class="help-block"><?php if (isset($errors['invoices[paid]'])) e($errors['invoices[paid]']); ?></span>
		</div>
	
		<div class="form-group <?php e(isset($errors['invoices[reminder1]'])?'has-error':''); ?>">
			<label class="control-label" for="invoices[reminder1]">First reminder</label>
			<input class="form-control" name="invoices[reminder1]" type="date" value="<?php e($data['invoices']['reminder1']); ?>" id="invoices[reminder1]" />
			<span class="help-block"><?php if (isset($errors['invoices[reminder1]'])) e($errors['invoices[reminder1]']); ?></span>
		</div>
	
		<div class="form-group <?php e(isset($errors['invoices[reminder2]'])?'has-error':''); ?>">
			<label class="control-label" for="invoices[reminder2]">Second reminder</label>
			<input class="form-control" name="invoices[reminder2]" type="date" value="<?php e($data['invoices']['reminder2']); ?>" id="invoices[reminder2]" />
			<span class="help-block"><?php if (isset($errors['invoices[reminder2]'])) e($errors['invoices[reminder2]']); ?></span>
		</div>
	<?php } ?>

	<br />

	<div class="form-group <?php e(isset($errors['invoiceline_id'])?'has-error':''); ?>">
	<table class="table">
		<thead>
			<tr>
				<th class="name" colspan="2">Invoice lines</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($invoicelines as $row): ?>
			<tr>
				<td class="name"><span><input name="invoiceline_id[]" type="checkbox" value="<?php if(isset($row['invoicelines']['id'])) e($row['invoicelines']['id']);?>" <?php if($row['invoicelines']['selected']) e('checked');?> /> &nbsp; <?php e($row['invoicelines']['name']);?></span></td>
				<td class="money"><span><?php e($row['invoicelines']['subtotal']);?></span></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<span class="help-block"><?php if (isset($errors['invoiceline_id'])) e($errors['invoiceline_id']); ?></span>
	</div>

	<br /><br />
  
	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 