<?php Buffer::set('title','Add invoice'); ?>
<div class="page-header">
	<h3><a href="/">Home</a> / <a href="invoices">Invoices</a></h3>
  	<h1>Add invoice</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">

	<div class="form-group <?php e(isset($errors['invoices[number]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[number]">Number</label>
		<input class="form-control" name="invoices[number]" type="number" value="<?php e($highest_invoice_number+1); ?>" id="invoices[number]" disabled />
		<span class="help-block"><?php if (isset($errors['invoices[number]'])) e($errors['invoices[number]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['invoices[date]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[date]">Date</label>
		<input class="form-control" name="invoices[date]" type="date" value="<?php e($data['invoices']['date']); ?>" id="invoices[date]" />
		<span class="help-block"><?php if (isset($errors['invoices[date]'])) e($errors['invoices[date]']); ?></span>
	</div>  

	<div class="form-group <?php e(isset($errors['invoices[name]'])?'has-error':''); ?>">
		<label class="control-label" for="invoices[name]">Name</label>
		<input class="form-control" name="invoices[name]" type="text" value="<?php e($data['invoices']['name']); ?>" id="invoices[name]" />
		<span class="help-block"><?php if (isset($errors['invoices[name]'])) e($errors['invoices[name]']); ?></span>
	</div>

	<br />

	<table class="table">
		<thead>
			<tr>
				<th class="name" colspan="2">Invoice lines</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($hours as $row): ?>
			<tr>
				<td class="name"><span><input name="hours[]" type="checkbox" value="<?php e($row['hours']['id']);?>" checked /> &nbsp; <?php e($row['hours']['name']);?></span></td>
				<td class="money"><span><?php e($row['hours']['subtotal']);?></span></td>
			</tr>
			<?php endforeach; ?>
			<?php foreach ($deliveries as $row): ?>
			<tr>
				<td class="name"><span><input name="deliveries[]" type="checkbox" value="<?php e($row['deliveries']['id']);?>" checked /> &nbsp; <?php e($row['deliveries']['name']);?></span></td>
				<td class="money"><span><?php e($row['deliveries']['subtotal']);?></span></td>
			</tr>
			<?php endforeach; ?>
			<?php foreach ($subscriptionperiods as $row): ?>
			<tr>
				<td class="name"><span><input name="subscriptionperiods[]" type="checkbox" value="<?php e($row['subscriptionperiods']['id']);?>" checked /> &nbsp; <?php e($row['invoicelines']['name']);?></span></td>
				<td class="money"><span><?php e($row['hours']['subtotal']);?></span></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<br /><br />

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>

</form> 
