<?php Buffer::set('title','Password forgotten'); ?>
<h1>Password forgotten</h1>
<p>No worries! Just enter your e-mail below and we will send you a password reset link.</p>
<form method="post">
    <div class="form-group <?php e(isset($errors['username'])?'has-error':''); ?>">
		<label class="control-label" for="username">Email</label>
		<input class="form-control" name="username" type="email" value="<?php e($data['username']); ?>" id="username" />
		<span class="help-block"><?php if (isset($errors['username'])) e($errors['username']); ?></span>
	</div>
    <div class="form-group">
        <button type="submit" class="btn-primary">Submit</button>
    </div>
    <?php Session::getCsrfInput(); ?>
</form>

<p><a href="auth/login">Login</a></p>