<div class="page-header">
  <h1>New user</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
  
	<div class="form-group <?php e(isset($errors['users[username]'])?'has-error':''); ?>">
		<label class="control-label" for="users[username]">Username</label>
		<input class="form-control" name="users[username]" type="text" value="<?php e($data['users']['username']); ?>" id="users[username]" />
		<span class="help-block"><?php if (isset($errors['users[username]'])) e($errors['users[username]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['users[name]'])?'has-error':''); ?>">
		<label class="control-label" for="users[name]">Name</label>
		<input class="form-control" name="users[name]" type="text" value="<?php e($data['users']['name']); ?>" id="users[name]" />
		<span class="help-block"><?php if (isset($errors['users[name]'])) e($errors['users[name]']); ?></span>
	</div>
  
	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 