<?php Buffer::set('title','Add Customer'); ?>
<div class="page-header">
	<h3><a href="/">Home</a> / <a href="customers">Customers</a></h3>
	<h1>Add customer</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
  
	<div class="form-group <?php e(isset($errors['customers[name]'])?'has-error':''); ?>">
		<label class="control-label" for="customers[name]">Name</label>
		<input class="form-control" name="customers[name]" type="text" value="<?php e($data['customers']['name']); ?>" id="customers[name]" />
		<span class="help-block"><?php if (isset($errors['customers[name]'])) e($errors['customers[name]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['customers[email]'])?'has-error':''); ?>">
		<label class="control-label" for="customers[email]">Email address</label>
		<input class="form-control" name="customers[email]" type="text" value="<?php e($data['customers']['email']); ?>" id="customers[email]" />
		<span class="help-block"><?php if (isset($errors['customers[email]'])) e($errors['customers[email]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['customers[contact]'])?'has-error':''); ?>">
		<label class="control-label" for="customers[contact]">Contact</label>
		<input class="form-control" name="customers[contact]" type="text" value="<?php e($data['customers']['contact']); ?>" id="customers[contact]" />
		<span class="help-block"><?php if (isset($errors['customers[contact]'])) e($errors['customers[contact]']); ?></span>
	</div>
  
	<div class="form-group <?php e(isset($errors['customers[address]'])?'has-error':''); ?>">
		<label class="control-label" for="customers[address]">Address</label>
		<textarea class="form-control" name="customers[address]" type="text" id="customers[address]"><?php e($data['customers']['address']); ?></textarea>
		<span class="help-block"><?php if (isset($errors['customers[address]'])) e($errors['customers[address]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['customers[language_id]'])?'has-error':''); ?>">
		<label class="control-label" for="customers[language_id]">Invoice language</label>
		<select class="form-control" name="customers[language_id]" id="customers[language_id]">
		<?php foreach ($languages as $language): ?>
			<option value="<?php e($language['languages']['id']); ?>"<?php e($language['languages']['id']==$data['customers']['language_id']?' selected="selected"':''); ?>><?php e($language['languages']['name']); ?></option>
		<?php endforeach; ?>
		</select>
		<span class="help-block"><?php if (isset($errors['customers[language_id]'])) e($errors['customers[language_id]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['customers[tax_reverse_charge]'])?'has-error':''); ?>">
		<label class="control-label" for="customers[tax_reverse_charge]">Tax Reverse Charge</label>
		<input class="form-control" name="customers[tax_reverse_charge]" type="checkbox" <?php if($data['customers']['tax_reverse_charge']) e('checked'); ?> id="customers[tax_reverse_charge]" value="1" />
		<span class="help-block"><?php if (isset($errors['customers[tax_reverse_charge]'])) e($errors['customers[tax_reverse_charge]']); ?></span>
	</div>

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 