<?php Buffer::set('title','deliveries'); ?>
<h3><a href="/">Home</a></h3>
<h1>Deliveries <a href="deliveries/add" class="btn-primary">Add delivery</a></h1>

<p>Enter your deliveries in the table below. We will automagically create invoicelines for them. Happy invoicing!</p>

<table class="table responsive-minimal">
  <thead>
    <tr>
      <th class="date <?php if($order=='date') e('selected'); ?>" order="/deliveries/date/desc">Date</th>
      <th class="name <?php if($order=='name') e('selected'); ?>" order="/deliveries/name/asc">Name</th>
      <th class="text <?php if($order=='customer_id') e('selected'); ?>" order="/deliveries/customer_id/asc">Customer</th>
      <th class="money <?php if($order=='subtotal') e('selected'); ?>" order="/deliveries/subtotal/desc">Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($data as $row): ?>
    <tr class="hover" onclick="window.location.href='deliveries/view/<?php e($row['deliveries']['id']);?>';">
      <td class="date"><span><?php e($row['deliveries']['date']);?></span></td>
      <td class="name"><span><?php e($row['deliveries']['name']);?></span></td>
      <td class="text"><span><?php if(isset($row['deliveries']['customer_id'])) { ?><a href="projects/view/<?php e($row['deliveries']['customer_id']); ?>"><?php e($customers[$row['deliveries']['customer_id']]);?></a><?php } ?></span></td>
      <td class="money"><span><?php if($row['deliveries']['subtotal']) e($row['deliveries']['subtotal']); else e('0'); ?></span></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<p><a class="btn-primary" href="deliveries/add">Add delivery</a></p>