<?php Buffer::set('title','Statistics'); ?>
<h3>Home</h3>
<h1>Statistics</h1>

<p>You currently receive <?php e(round($subscriptionIncome)); ?> euro per month from <a href="/subscriptions">subscriptions</a>.<br />The <?php e(date('Y')); ?> total of <a href="/invoices">invoices</a> is <?php e(round($incomeThisYear/1000,1)); ?>k euro and you have <?php e(round($incomeThisYearAddon/1000,1)); ?>k euro of uninvoiced work.<br />This creates a total of <?php e(round(($incomeThisYear + $incomeThisYearAddon)/1000,1)); ?>k euro. Last year you received <?php e(round($incomeLastYear/1000,1)); ?>k euro.<p>

<br />
<div>
<?php if($sumhourspertype_thisyear) { ?>
<div class="col50">
<table>
    <tr>
        <th class="name" colspan="3">Hours this year (<?php e(round($totalhours_thisyear)); ?>)</th>
    </tr>
    <?php foreach ($sumhourspertype_thisyear as $name=>$sum): ?>
        <tr>
            <td class="precentage"><span><?php e(round($sum/$totalhours_thisyear*100)); ?>%</span></td>
            <td><span><?php if($name) e($name); else e('Other'); ?></span></td>
            <td><span><?php e(round($sum)); ?> hours</span></td>
        </tr>
    <?php endforeach; ?>
</table>
</div>
<?php } ?>

<?php if($sumhourspertype_lastyear) { ?>
<div class="col50">
<table>
    <tr>
        <th class="name" colspan="3">Hours last year (<?php e(round($totalhours_lastyear)); ?>)</th>
    </tr>
    <?php foreach ($sumhourspertype_lastyear as $name=>$sum): ?>
        <tr>
            <td class="precentage"><span><?php e(round($sum/$totalhours_lastyear*100)); ?>%</span></td>
            <td><span><?php if($name) e($name); else e('Other'); ?></span></td>
            <td><span><?php e(round($sum)); ?> hours</span></td>
        </tr>
    <?php endforeach; ?>
</table>
</div>
<?php } ?>
</div>