<?php Buffer::set('title','Statistics'); ?>
<h3>Home</h3>
<h1 style="padding-right: 20px;">Statistics of <?php e($year); ?> <a href="statistics/<?php e($year-1); ?>" class="down"></a><a href="statistics/<?php if($year < date('Y')) e($year+1); else e($year); ?>" class="up <?php if(($year+1) > date('Y')) e('inactive'); ?>"></a></h1>

<p class="lead">You receive(d) &euro; <?php e(round($subscriptionIncome)); ?> per month from <a href="/subscriptions">subscriptions</a>.<br />The <?php e($year); ?> total of <a href="/invoices">invoices</a> is <?php e(round($incomeThisYear/1000,1)); ?>k euro<?php if(isset($incomeThisYearAddon) && $incomeThisYearAddon)  {?> and you have <?php e(round($incomeThisYearAddon/1000,1)); ?>k euro of uninvoiced work. This creates a total of <?php e(round(($incomeThisYear + $incomeThisYearAddon)/1000,1)); ?>k euro<?php } ?>.</p>

<div><?php e($maxyearincome/1000); ?>k</div>
<?php 
$graph_width = 300;
$graph_height = 100;
?>
<svg viewBox="0 0 <?php e($graph_width);?> <?php e($graph_height);?>" class="chart" style="border-left: 1px solid #aaa; border-bottom: 1px solid #aaa;">
  <polyline
     id="totalincome_graph"
     fill="#5b4f96"
     stroke="none"
     stroke-width="0.5"
     points="0,<?php e($graph_height);?>
    <?php 
    $invoiced = 0;
    foreach ($totalincome_graph as $datapoint):
        $invoiced = $invoiced + $datapoint['']['invoiced'];
        e(($datapoint['']['day_number']*$graph_width).",".($graph_height-($invoiced/$maxyearincome)*$graph_height)." ");
    endforeach; 
    e(($relativeday*$graph_width).",".($graph_height-($invoiced/$maxyearincome)*$graph_height)." ");
    e(($relativeday*$graph_width).",".$graph_height);
    $totalinvoiced = $invoiced;
    ?>
       "/>
  <polyline
     id="subscriptionincome_graph"
     fill="#928AB9"
     stroke="none"
     stroke-width="0.5"
     points="0,<?php e($graph_height);?>
    <?php 
    $invoiced = 0;
    foreach ($subscriptionincome_graph as $datapoint):
        $invoiced = $invoiced + $datapoint['']['invoiced'];
        e(($datapoint['']['day_number']*$graph_width).",".($graph_height-($invoiced/$maxyearincome)*$graph_height)." ");
    endforeach; 
    e(($relativeday*$graph_width).",".($graph_height-($invoiced/$maxyearincome)*$graph_height)." ");
    e(($relativeday*$graph_width).",".$graph_height);
    $totalsubscriptions = $invoiced;
    ?>
       "/>
  <polyline
     id="totalpaid_graph"
     fill="none"
     stroke="#26cab7"
     stroke-width="0.5"
     points="0,<?php e($graph_height);?>
    <?php 
    $invoiced = 0;
    foreach ($totalpaid_graph as $datapoint):
        $invoiced = $invoiced + $datapoint['']['invoiced'];
        e(($datapoint['']['day_number']*$graph_width).",".($graph_height-($invoiced/$maxyearincome)*$graph_height)." ");
    endforeach; 
    e(($relativeday*$graph_width).",".($graph_height-($invoiced/$maxyearincome)*$graph_height));
    $totalpaid = $invoiced;
    ?>
       "/>
</svg>
<div><span style="float: right;">dec <?php e($year); ?></span></div>
<ul class="legend">
    <li><div class="square purple"></div> invoiced <span>(<?php e(round($totalinvoiced/1000,1)); ?>k)</span></li>
    <li><div class="square lightpurple"></div> subscriptions <span>(<?php e(round($totalsubscriptions/1000,1)); ?>k)</span></li>
    <li><div class="square green"></div> paid <span>(<?php e(round($totalpaid/1000,1)); ?>k)</span></li>
</ul>

<div>
<?php if($sumhourspertype_thisyear) { ?>
<div class="col50">
<table>
    <tr>
        <th class="name" colspan="3">Hours per type (<?php e(round($totalhours_thisyear)); ?>)</th>
    </tr>
    <?php foreach ($sumhourspertype_thisyear as $name=>$sum): ?>
        <tr>
            <td class="precentage"><span><?php e(round($sum/$totalhours_thisyear*100)); ?>%</span></td>
            <td><span><?php if($name) e($name); else e('Other'); ?></span></td>
            <td><span><?php e(round($sum)); ?> hours</span></td>
        </tr>
    <?php endforeach; ?>
</table>
</div>
<?php } ?>


<?php if($sumsubscriptionspertype_thisyear) { ?>
<div class="col50">
<table>
    <tr>
        <th class="name" colspan="3">Subscriptions per type (&euro; <?php e(round($subscriptionIncome)); ?>)</th>
    </tr>
    <?php foreach ($sumsubscriptionspertype_thisyear as $sumsubscriptiontype): ?>
        <tr>
            <td class="precentage"><span><?php e($sumsubscriptiontype['subscriptiontypes']['times']); ?>x</span></td>    
            <td><span><a href="subscriptiontypes/view/<?php e($sumsubscriptiontype['subscriptiontypes']['id']); ?>"><?php e($sumsubscriptiontype['subscriptiontypes']['name']); ?></a></span></td>
            <td class="money"><span><?php e(number_format($sumsubscriptiontype['subscriptiontypes']['sum'],2)); ?></span></td>
        </tr>
    <?php endforeach; ?>
</table>
</div>
<?php } ?>

</div>