<!DOCTYPE html>
<html>
  <head>
    <base href="<?php e(Router::getBaseUrl());?>">
    <title><?php Buffer::get('title');?> | InvoiceLion</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="img/icon-196x196.png">
    <link rel="shortcut icon" sizes="196x196" href="img/icon-196x196.png">
    <link rel="apple-touch-icon" href="img/homescreenicon.png">

    <link href="css/default.css" rel="stylesheet" type="text/css">
  </head>
  <body class="showmenu">
    <div class="main">

      <div class="content">
        <?php foreach ($flash as $type=>$text): ?> 
          <div class="alert alert-<?php e($type); ?>">
            <button type="button" class="close">x</button>
            <div class="message">
              <?php e($text); ?>
            </div>
          </div>
        <?php endforeach; ?>
   
        <?php Buffer::get('html');?>

        <div class="nav">
          <h3>Menu</h3>
          <a href="/"><img src="/img/icon.svg" /><span>Dashboard</span></a><br /> 
          <a href="statistics"><img src="/img/chart-bar.svg" /><span>Statistics</span></a><br />  
          <?php if($tenant['tenants']['hours_active']) {?><a href="hours"><img src="/img/clock.svg" /><span>Hours</span></a><br /><?php }?>
          <a href="deliveries"><img src="/img/box-alt.svg" /><span>Deliveries</span></a><br />
          <?php if($tenant['tenants']['subscriptions_active']) {?><a href="subscriptions"><img src="/img/repeat.svg" /><span>Subscriptions</span></a><br /><?php }?>
          <a href="invoices"><img src="/img/file-invoice-dollar.svg" /><span>Invoices</span></a><br />        
          <a href="customers"><img src="/img/address-book.svg" /><span>Customers</span></a><br />
          <a href="tenants/view"><img src="/img/cog.svg" /><span>Settings</span></a><br />
          <?php $username = isset($_SESSION['user']) ? $_SESSION['user']['username'] : false?>
          <a href="users/view/<?php e($_SESSION['user']['id']); ?>" title="User"><img src="/img/user.svg" /><span><?php e($username);?></span></a> 
          <a href="auth/logout" title="Logout"><img src="/img/power-off.svg" /><span>Logout</span></a>
        </div>

      </div>

      <div class="icons">
        <div>
          <a href="/" id="branding" title="InvoiceLion"><span></span></a>
          <a href="/" title="Dashboard">
            <div class="img" style="background-image: url(/img/icon.svg);"></div>
            <div class="img" style="background-image: url(/img/icon-green.svg);"></div>
            <span>Dashboard</span>
          </a>
          <a href="hours" title="Hours">
            <div class="img" style="background-image: url(/img/clock.svg);"></div>
            <div class="img" style="background-image: url(/img/clock-green.svg);"></div>
            <span>Hours</span>
          </a>
          <a href="deliveries" title="Deliveries">
            <div class="img" style="background-image: url(/img/box-alt.svg);"></div>
            <div class="img" style="background-image: url(/img/box-alt-green.svg);"></div>
            <span>Deliveries</span>
          </a>
          <a href="subscriptions" title="Subscriptions">
            <div class="img" style="background-image: url(/img/repeat.svg);"></div>
            <div class="img" style="background-image: url(/img/repeat-green.svg);"></div>
            <span>Subscriptions</span>
          </a>
          <a href="invoices" title="Invoices">
            <div class="img" style="background-image: url(/img/file-invoice-dollar.svg);"></div>
            <div class="img" style="background-image: url(/img/file-invoice-dollar-green.svg);"></div>
            <span>Invoices</span>
          </a>
          <a href="customers" title="Customers">
            <div class="img" style="background-image: url(/img/address-book.svg);"></div>
            <div class="img" style="background-image: url(/img/address-book-green.svg);"></div>
            <span>Customers</span>
          </a>
          <a href="settings/" class="onlydesktop" title="Settings">
            <div class="img" style="background-image: url(/img/cog.svg);"></div>
            <div class="img" style="background-image: url(/img/cog-green.svg);"></div>
            <span>Settings</span>
          </a>
          <a href="menu/" class="onlymobile" title="More">
            <div class="img" style="background-image: url(/img/ellipsis-h.svg);"></div>
            <div class="img" style="background-image: url(/img/ellipsis-h-green.svg);"></div>
            <span>Menu</span>
          </a>

          <div class="bottom">
            <?php $username = isset($_SESSION['user']) ? $_SESSION['user']['username'] : false?>
            <a href="users/view/<?php e($_SESSION['user']['id']); ?>" title="User">
              <div class="img" style="background-image: url(/img/user.svg);"></div>
              <div class="img" style="background-image: url(/img/user-green.svg);"></div>
              <span><?php e(substr($username,0,8)."...");?></span>
            </a> 
            <a href="auth/logout" title="Logout">
              <div class="img" style="background-image: url(/img/power-off.svg);"></div>
              <div class="img" style="background-image: url(/img/power-off-green.svg);"></div>
              <span>Logout</span>
            </a>
          </div>
        </div>
      </div>
    </div>


    <script>
      var elements = document.querySelectorAll('th[order]');
      elements.forEach(element => {
        element.addEventListener("click", function(){
          document.location.href=element.attributes['order'].nodeValue;
          if(document.location.href.endsWith(element.attributes['order'].nodeValue)){
            if(element.attributes['order'].nodeValue.endsWith('/desc')) {
              document.location.href=element.attributes['order'].nodeValue.replace('/desc','/asc');
            } else {
              document.location.href=element.attributes['order'].nodeValue.replace('/asc','/desc');
            }
          }
        }); 
      });

      var elements = document.querySelectorAll('.alert button');
      elements.forEach(element => {
        element.addEventListener("click", function(){
          element.parentNode.style.display = 'none';
        }); 
      });
      
    </script>

  </body>
</html>
