<!DOCTYPE html>
<html>
  <head>
    <base href="<?php e(Router::getBaseUrl());?>">
    <title>Menu | InvoiceLion</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="img/icon-196x196.png">
    <link rel="shortcut icon" sizes="196x196" href="img/icon-196x196.png">
    <link rel="apple-touch-icon" href="img/homescreenicon.png">

    <link href="css/default.css" rel="stylesheet" type="text/css">
  </head>
  <body class="default">

    <div class="menu">
        
        <?php Buffer::get('html');?>

    </div>

</body>
</html>