<?php Buffer::set('title','Settings'); ?>
<h3>Home</h3>
<h1>Settings</h1>

<p>Below you will find your preferences. You can set here if you want to enable time tracking, and you can enter the values that show up on your invoices.</p>

<br />

<ul>
    <li><a href="/settings/general/view">General Settings</a></li>
    <li><a href="/settings/company/view">Company Settings</a></li>
    <li><a href="/settings/invoice/view">Invoice Settings</a></li>
</ul>