<?php Buffer::set('title', 'Settings');?>
<h3>Home</h3>
<h1>Settings</h1>

<p>Below you will find your preferences. You can set here if you want to enable time tracking (hours) and subscriptions, and you can customize (the data on) your invoices.</p>

<br />

<ul>
    <li><a href="/settings/general/view">General Settings</a></li>
    <li><a href="/settings/company/view">Company Settings</a></li>
    <li><a href="/settings/invoice/view">Invoice Settings</a></li>
    <ul>
		<?php foreach ($languages as $language): ?>
            <li><a href="/settings/languages/view/<?php e($language['languages']['id']);?>">Language Settings (<?php e(strtoupper($language['languages']['code']));?>)</a></li>
		<?php endforeach;?>
    </ul>
</ul>