<?php Buffer::set('title','Settings'); ?>
<h3><a href="/">Home</a> / Settings</h3>
<h1>General settings</h1>

<?php include('pages/settings/settingstabs.php'); ?>

<div>
        <dl>
            <dt>Currency</dt>
            <dd>        
                <?php e($currency['currencies']['name']); ?>
            </dd>
        </dl>
        <dl>
            <dt>Time tracking</dt>
            <dd>        
                <?php if($data['tenants']['hours_active']) e('yes'); else e('no'); ?>
            </dd>
        </dl>
        <dl>
            <dt>Subscriptions</dt>
            <dd>        
                <?php if($data['tenants']['subscriptions_active']) e('yes'); else e('no'); ?>
            </dd>
        </dl>
        <dl>
            <dt>Default tax percentage</dt>
            <dd>        
                <?php e($data['tenants']['default_tax_percentage']); ?>
            </dd>
        </dl>
        <dl>
            <dt>Default hourly fee</dt>
            <dd>        
                <?php e($data['tenants']['default_hourly_fee']); ?>
            </dd>
        </dl>
        <dl>
            <dt>Integrity</dt>
            <dd><a href="settings/general/check">check</a></dd>
        </dl>
        <dl>
            <dt>Projects (<a href="projects/index">manage</a>)</dt>
            <dd>        
                <?php if ($projects): foreach ($projects as $row): ?>
                <a href="projects/view/<?php e($row['projects']['id']); ?>" class="tag"><?php e($row['projects']['name']); ?></a>
                <?php endforeach; else: e('-'); endif; ?>
            </dd>
        </dl>
        <dl>
            <dt>Hour types (<a href="hourtypes/index">manage</a>)</dt>
            <dd>        
                <?php if ($hourtypes): foreach ($hourtypes as $row): ?>
                <a href="hourtypes/view/<?php e($row['hourtypes']['id']); ?>" class="tag"><?php e($row['hourtypes']['name']); ?></a>
                <?php endforeach; else: e('-'); endif; ?>
            </dd>
        </dl>
        <dl>
            <dt>Subscription types (<a href="subscriptiontypes/index">manage</a>)</dt>
            <dd>        
                <?php if ($subscriptiontypes): foreach ($subscriptiontypes as $row): ?>
                <a href="subscriptiontypes/view/<?php e($row['subscriptiontypes']['id']); ?>" class="tag"><?php e($row['subscriptiontypes']['name']); ?></a>
                <?php endforeach; else: e('-'); endif; ?>
            </dd>
        </dl>
</div>

<br />

<p>
	<a class="btn btn-primary" href="settings/general/edit">Edit</a>
</p>