<?php Buffer::set('title','Settings'); ?>
<h3><a href="/">Home</a> / <a href="/settings/">Settings</a></h3>
<h1>Edit invoice settings</h1>

<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">
   
		<div class="form-group <?php e(isset($errors['tenants[payment_period]'])?'has-error':''); ?>">
		<label class="control-label" for="tenants[payment_period]">Payment period (in days)</label>
		<input class="form-control" name="tenants[payment_period]" type="number" id="tenants[payment_period]" value="<?php e($data['tenants']['payment_period']); ?>"/>
		<span class="help-block"><?php if (isset($errors['tenants[payment_period]'])) e($errors['tenants[payment_period]']); ?></span>
		</div>

		<div class="form-group <?php e(isset($errors['tenants[reminder_period]'])?'has-error':''); ?>">
		<label class="control-label" for="tenants[reminder_period]">Reminder period (in days)</label>
		<input class="form-control" name="tenants[reminder_period]" type="number" id="tenants[reminder_period]" value="<?php e($data['tenants']['reminder_period']); ?>"/>
		<span class="help-block"><?php if (isset($errors['tenants[reminder_period]'])) e($errors['tenants[reminder_period]']); ?></span>
		</div>

		<div class="form-group <?php e(isset($errors['tenants[invoice_email]'])?'has-error':''); ?>">
		<label class="control-label" for="tenants[invoice_email]">Email address (for outgoing invoices)</label>
		<input class="form-control" name="tenants[invoice_email]" type="text" id="tenants[invoice_email]" value="<?php e($data['tenants']['invoice_email']); ?>" />
		<span class="help-block"><?php if (isset($errors['tenants[invoice_email]'])) e($errors['tenants[invoice_email]']); ?></span>
    	</div>

    <div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form>