<?php Buffer::set('title','Settings'); ?>
<h3>Home / <a href="/settings/">Settings</a></h3>
<h1>Invoice settings</h1>

<p>Below you will find your preferences. You can set here if you want to enable time tracking, and you can enter the values that show up on your invoices.</p>

<br />

<div>

    <dl>
        <dt>Payment period (in days)</dt>
        <dd><?php e($data['tenants']['payment_period']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Reminder period (in days)</dt>
        <dd><?php e($data['tenants']['reminder_period']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Logo (<a href="tenants/change/logo_image/2.5">change</a>)</dt>
        <dd><div style="height: 3.5em; width: 50%; background: url('data:image/png;base64,<?php e(base64_encode($data['tenants']['logo_image']));?>') left center / contain no-repeat;"></div></dd>
    </dl>
    <dl>
        <dt>Signature (<a href="tenants/change/signature_image/5.5">change</a>)</dt>
        <dd><div style="height: 3.5em; width: 50%; background: url('data:image/png;base64,<?php e(base64_encode($data['tenants']['signature_image']));?>') left center / contain no-repeat;"></div></dd>
    </dl>
    <dl>
        <dt>Invoice styles</dt>
        <dd><?php e(substr($data['tenants']['invoice_styles']?:'-',0,100));?>...</dd>
    </dl>
    <dl>
        <dt>Invoice template</dt>
        <dd><?php e(substr($data['tenants']['invoice_template']?:'-',0,100));?>...</dd>
    </dl>
    <dl>
        <dt>Invoice page number</dt>
        <dd><?php e(substr($data['tenants']['invoice_page_number']?:'-',0,100));?>...</dd>
    </dl>

</div>

<br />

<p>
	<a class="btn btn-primary" href="settings/invoice/edit">Edit</a>
</p>