<?php Buffer::set('title','Settings'); ?>
<h3>Home / <a href="/settings/">Settings</a></h3>
<h1>Company settings</h1>

<div>
    <dl>
        <dt>Company name</dt>
        <dd><?php e($data['tenants']['name']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Contact name</dt>
        <dd><?php e($data['tenants']['contact']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Address</dt>
        <dd><pre><?php e($data['tenants']['address']?:'-');?></pre></dd>
    </dl>
    <dl>
        <dt>Email address</dt>
        <dd><?php e($data['tenants']['email']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Phone</dt>
        <dd><?php e($data['tenants']['phone']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Bank account number</dt>
        <dd><?php e($data['tenants']['bank_account_number']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Bank account name</dt>
        <dd><?php e($data['tenants']['bank_account_name']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Bank name</dt>
        <dd><?php e($data['tenants']['bank_name']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Bank BIC</dt>
        <dd><?php e($data['tenants']['bank_bic']?:'-');?></dd>
    </dl>
    <dl>
        <dt>Bank city</dt>
        <dd><?php e($data['tenants']['bank_city']?:'-');?></dd>
    </dl>
    <dl>
        <dt>COC number</dt>
        <dd><?php e($data['tenants']['coc_number']?:'-');?></dd>
    </dl>
    <dl>
        <dt>VAT number</dt>
        <dd><?php e($data['tenants']['vat_number']?:'-');?></dd>
    </dl>
</div>

<br />

<p>
	<a class="btn btn-primary" href="settings/company/edit">Edit</a>
</p>