<div class="page-header">
	<h3><a href="/">Home</a> / <a href="hours">Hours</a></h3>
  	<h1>Add hours</h1>
</div>
<?php if (isset($error)): ?><div class="alert alert-danger"><button type="button" class="close">x</button><div class="message"><?php e($error); ?></div></div><?php endif; ?>
<form method="post">

	<?php if(count($projects)>0): ?>
		<div class="form-group <?php e(isset($errors['hours[project_id]'])?'has-error':''); ?>">
			<label class="control-label" for="hours[project_id]">Project</label>
			<select class="form-control" name="hours[project_id]" id="hours[project_id]" onchange="document.getElementById('hours[customer_id]').value = this.options[this.selectedIndex].getAttribute('customer-value'); if(this.options[this.selectedIndex].getAttribute('hourly-fee')!='0.00') document.getElementById('hours[hourly_fee]').value = this.options[this.selectedIndex].getAttribute('hourly-fee');">
				<option value=""<?php e(''==$data['hours']['project_id']?' selected="selected"':''); ?>></option>
				<?php foreach ($projects as $project): ?>
				<option value="<?php e($project['projects']['id']); ?>" customer-value="<?php e($project['projects']['customer_id']); ?>" hourly-fee="<?php e($project['projects']['default_hourly_fee']); ?>" <?php e($project['projects']['id']==$data['hours']['project_id']?' selected="selected"':''); ?>><?php e($project['projects']['name']); ?></option>
				<?php endforeach; ?>
			</select>
			<span class="help-block"><?php if (isset($errors['hours[project_id]'])) e($errors['hours[project_id]']); ?></span>
		</div>
	<?php else: ?>
		<input name="hours[project_id]" type="hidden" value="" />
	<?php endif; ?>

	<div class="form-group <?php e(isset($errors['hours[customer_id]'])?'has-error':''); ?>">
		<label class="control-label" for="hours[customer_id]">Customer <a onclick="this.parentNode.nextElementSibling.selectedIndex = 0; this.parentNode.parentNode.nextElementSibling.style.display = 'block'; this.parentNode.parentNode.style.display = 'none'; document.getElementById('hours[add_customer]').focus();">add</a></label>
		<select class="form-control" name="hours[customer_id]" id="hours[customer_id]">
			<option value=""<?php e(''==$data['hours']['customer_id']?' selected="selected"':''); ?>></option>
			<?php foreach ($customers as $key => $value): ?>
			<option value="<?php e($key); ?>"<?php e($key==$data['hours']['customer_id']?' selected="selected"':''); ?>><?php e($value); ?></option>
			<?php endforeach; ?>
		</select>
		<span class="help-block"><?php if (isset($errors['hours[customer_id]'])) e($errors['hours[customer_id]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['hours[add_customer]'])?'has-error':''); ?>" style="display: none;">
		<label class="control-label" for="hours[add_customer]">Customer <a onclick="this.parentNode.nextElementSibling.value = ''; this.parentNode.parentNode.previousElementSibling.style.display = 'block'; this.parentNode.parentNode.style.display = 'none';">cancel</a></label>
		<input class="form-control" name="hours[add_customer]" type="text" value="<?php e($data['hours']['add_customer']); ?>" id="hours[add_customer]" />
		<span class="help-block"><?php if (isset($errors['hours[add_customer]'])) e($errors['hours[add_customer]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['hours[date]'])?'has-error':''); ?>">
		<label class="control-label" for="hours[date]">Date</label>
		<input class="form-control" name="hours[date]" type="date" value="<?php e($data['hours']['date']); ?>" id="hours[date]" />
		<span class="help-block"><?php if (isset($errors['hours[date]'])) e($errors['hours[date]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['hours[hours_worked]'])?'has-error':''); ?>">
		<label class="control-label" for="hours[hours_worked]">Number of hours</label>
		<input class="form-control" name="hours[hours_worked]" type="number" step="0.25" value="<?php e($data['hours']['hours_worked']); ?>" id="hours[hours_worked]" />
		<span class="help-block"><?php if (isset($errors['hours[hours_worked]'])) e($errors['hours[hours_worked]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['hours[hourly_fee]'])?'has-error':''); ?>">
		<label class="control-label" for="hours[hourly_fee]">Hourly fee</label>
		<input class="form-control" name="hours[hourly_fee]" type="number" step="0.01" value="<?php e($data['hours']['hourly_fee']); ?>" id="hours[hourly_fee]" />
		<span class="help-block"><?php if (isset($errors['hours[hourly_fee]'])) e($errors['hours[hourly_fee]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['hours[tax_percentage]'])?'has-error':''); ?>">
		<label class="control-label" for="hours[tax_percentage]">tax percentage</label>
		<input class="form-control" name="hours[tax_percentage]" type="number" step="0.01" value="<?php e($data['hours']['tax_percentage']); ?>" id="hours[tax_percentage]" />
		<span class="help-block"><?php if (isset($errors['hours[tax_percentage]'])) e($errors['hours[tax_percentage]']); ?></span>
	</div>

	<div class="form-group <?php e(isset($errors['hours[name]'])?'has-error':''); ?>">
		<label class="control-label" for="hours[name]">Name</label>
		<input class="form-control" name="hours[name]" type="text" value="<?php e($data['hours']['name']); ?>" id="hours[name]" />
		<span class="help-block"><?php if (isset($errors['hours[name]'])) e($errors['hours[name]']); ?></span>
	</div>

	<?php if(count($hourtypes)>0): ?>
		<div class="form-group <?php e(isset($errors['hours[type]'])?'has-error':''); ?>">
			<label class="control-label" for="hours[type]">Hour type</label>
			<select class="form-control" name="hours[type]" id="hours[type]">
				<option value=""<?php e(''==$data['hours']['type']?' selected="selected"':''); ?>></option>
				<?php foreach ($hourtypes as $key => $value): ?>
				<option value="<?php e($key); ?>"<?php e((($key==$data['hours']['type']) || (!$data['hours']['type'] && $value=='Productie'))?' selected="selected"':''); ?>><?php e($value); ?></option>
				<?php endforeach; ?>
			</select>
			<span class="help-block"><?php if (isset($errors['hours[type]'])) e($errors['hours[type]']); ?></span>
		</div>
	<?php else: ?>
		<input name="hours[type]" type="hidden" value="" />
	<?php endif; ?>
  
	<div class="form-group <?php e(isset($errors['hours[comment]'])?'has-error':''); ?>">
		<label class="control-label" for="hours[comment]">Comment</label>
		<textarea id="hours[comment]" class="form-control" name="hours[comment]"><?php e($data['hours']['comment']); ?></textarea>
		<span class="help-block"><?php if (isset($errors['hours[comment]'])) e($errors['hours[comment]']); ?></span>
	</div>

	<div class="form-group">
		<button class="btn btn-primary" type="submit">Save</button>
	</div>
	<?php Session::getCsrfInput(); ?>
</form> 